### ISSUE TITLE
Please don't use magic strings / numbers / etc

### ISSUE THREAD

**Issue by vitalk** [anastasiakoroto/LX_Task_2#2]
https://github.com/anastasiakoroto/LX_Task_2/blob/db981d34bd62d9fa891c2129ae3f0b3a7972be90/task_2.py#L73

Explicitly use constants if required and follow python idioms, e.g. 

```
>>> bool(1)
True
>>> bool(0)
False
>>>
```

**Comment by anastasiakoroto** [comment]
Okay, I‘ll make it right.

**Comment by anastasiakoroto** [comment]
Fixed (if i understand you correctly)
